name: Deploy to Docker and Github Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update version and commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          new_version=$(npm version patch -m "chore(release): v%s [skip ci]")
          echo "new-version=$new_version" >> $GITHUB_ENV

      - name: Set Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            wu529778790/telegram.shenzjd.com:${{ env.new-version }}
            wu529778790/telegram.shenzjd.com:latest

      - name: Push changes
        run: git push

      - name: Update Docker
        run: |
          curl -X POST https://api.shenzjd.com/docker \
          -H "Content-Type: application/json" \
          -d '{
            "dockerName": "wu529778790/telegram.shenzjd.com",
            "dockerComposeYml": "$(cat docker-compose.yml)"
          }'
